/**
 * record_parity_fixture.mjs
 *
 * Captures a real extraction and the server's answer to the same query, so the
 * numerical pipeline can be regression-tested offline.
 *
 * The live parity test needs both Source Cooperative and the production VM to
 * be reachable, which is fine on a developer machine but not something CI
 * should depend on. This script freezes one query: the arrays read out of the
 * Zarr store, and the payload /api/timeseries/multi/json returned for the same
 * point on the same day. client/tests/timeseriesProcessing.test.js then replays
 * the arrays through processSite() and checks the output still matches.
 *
 * Run from the client directory when the reference implementation changes:
 *
 *     node tests/fixtures/record_parity_fixture.mjs
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { openRegion, regionForLatitude, resolveSite, readVariable } from '../../src/utils/shiverStore.js';

const API = 'https://shiver.shef.ac.uk';
const OUT_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'parity_fixture.json');

// A fast-flowing outlet with a long record and a lot of source switching, so
// the fixture exercises gap bridging, outlier rejection and the daily average.
const CASE = {
  name: 'Jakobshavn Isbrae, single pixel',
  lat: 69.15,
  lon: -49.55,
  settings: {
    buffer: 0,
    variable: ['speed'],
    sources: [],
    gap_fill: 24,
    win_raw: 25,
    win_daily: 25,
    poly: 2,
  },
};

/** JSON has no NaN, so gaps travel as null. */
const encode = (values) => Array.from(values, (v) => (Number.isFinite(v) ? v : null));

const region = regionForLatitude(CASE.lat);
const regionInfo = await openRegion(region);
const site = resolveSite(regionInfo, CASE.lat, CASE.lon, CASE.settings.buffer);

if (site.error) throw new Error(`Site could not be resolved: ${site.error}`);

console.log(`Reading ${region} at ${CASE.lat}, ${CASE.lon} ...`);
const speed = await readVariable(regionInfo, 'speed', site);
const speedError = await readVariable(regionInfo, 'speed_error', site);

console.log('Querying the production API for the same point ...');
const response = await fetch(`${API}/api/timeseries/multi/json`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ roi: [[CASE.lat, CASE.lon]], ...CASE.settings }),
});
if (!response.ok) throw new Error(`API returned ${response.status}`);

const expected = (await response.json()).Site_0;
if (expected.status !== 'success') throw new Error(`API returned status ${expected.status}`);

const fixture = {
  _comment: 'Generated by tests/fixtures/record_parity_fixture.mjs - do not edit by hand.',
  recordedAt: new Date().toISOString(),
  case: CASE,
  region,
  datasetVersion: regionInfo.datasetVersion,
  lastUpdated: regionInfo.lastUpdated,
  input: {
    times: regionInfo.times,
    timeSeparation: encode(regionInfo.timeSeparation),
    dataSource: regionInfo.dataSource,
    validCount: Array.from(speed.validCount),
    speed: encode(speed.values),
    speedError: encode(speedError.values),
  },
  expected: expected.data,
};

writeFileSync(OUT_PATH, JSON.stringify(fixture));
console.log(`Wrote ${OUT_PATH} (${(Buffer.byteLength(JSON.stringify(fixture)) / 1024 / 1024).toFixed(2)} MB)`);
console.log(`  epochs=${regionInfo.times.length}  timeline=${expected.data.dates.length}  version=${regionInfo.datasetVersion}`);
